remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

title: SecOps Steward
description: Empowering administrators to create a more secure cloud!
github:
  repository_url: https://github.com/SecOpsSteward/SecOpsSteward
